import Head from 'next/head';
import { getSession } from "next-auth/react";
import React, { useEffect, useRef } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { ImageUrl, ListItems, Photos } from '../../components/Images';
import { activeTabSelectorFactory } from '../../redux/layouts/selectors';
import { setSwitchHeaderAction, setActivePageAction } from '../../redux/layouts/actions';
import BackendLayout from "../../components/Layout/BackendLayout";

export default function Index({ session, locale }: { session: any; locale: string }) {
    if (!session) return <></>;
    const dispatch = useDispatch();
    const activeTabLayout = useSelector(activeTabSelectorFactory('images'));
    const hiddenFileInput = useRef(null);
    const activeLayout = activeTabLayout;

    useEffect(() => {
        dispatch(setSwitchHeaderAction(null));
    }, []);

    const handleClick = () => {
        (hiddenFileInput as any).current.click();
    };

    const changeLayout = (type: string) => {
        dispatch(
            setActivePageAction({
                type: 'images',
                modifier: type
            })
        );
    };

    return (
        <>
            <Head>
                <title>MapKids - Images</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <h2 className="mt-10 text-lg font-medium intro-y">
                {activeLayout.tab  !== 'list' && <span onClick={() => dispatch(
                    setActivePageAction({
                        type: 'images',
                        modifier: 'list'
                    })
                )} className="cursor-pointer inline-block pl-[30px] text-[12px] mr-[10px] back-arrow" />}
                Images List
            </h2>
            {activeLayout.tab === 'list' && (
                <>
                    <div className="grid grid-cols-12 gap-6 mt-5">
                        <div className="flex flex-wrap items-center col-span-12 mt-2 intro-y sm:flex-nowrap">
                            <button
                                onClick={() => changeLayout('upload')}
                                className="btn bg-purple-800 inline-flex items-center justify-center py-2 px-3 rounded-md font-medium cursor-pointer text-white shadow-md mr-[10px]">
                                Upload New Images
                            </button>
                            <button
                                onClick={() => changeLayout('url')}
                                className="btn bg-purple-800 inline-flex items-center justify-center py-2 px-3 rounded-md font-medium cursor-pointer text-white shadow-md mr-[10px]">
                                Add Throw URL
                            </button>
                        </div>
                    </div>
                    <ListItems locale={locale} />
                </>
            )}
            {activeLayout.tab === 'photo' && <><Photos uploadedFiles={[]} photos={[]} /></>}
            {activeLayout.tab === 'url' && <><ImageUrl /></>}
        </>
    );
}
Index.Layout = BackendLayout;

export async function getServerSideProps(context: any) {
    const { locale } = context;
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: { destination: `/auth/signin` }
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
