import Head from 'next/head';
import { getSession } from "next-auth/react";
import React, { useEffect, useRef } from 'react';
import { useTranslations } from 'next-intl';
import { useDispatch, useSelector } from 'react-redux';
import { ListItems, Photos } from '../../components/Images';
import { activeTabSelectorFactory } from '../../redux/layouts/selectors';
import { setSwitchHeaderAction, setActivePageAction } from '../../redux/layouts/actions';
import BackendLayout from "../../components/Layout/BackendLayout";
import { itemCountSelector } from "../../redux/images/selectors";

export default function Index({ session, locale }: { session: any; locale: string }) {
    if (!session) return <></>;
    const count = useSelector(itemCountSelector);
    const t = useTranslations();
    const dispatch = useDispatch();
    const activeTabLayout = useSelector(activeTabSelectorFactory('images'));
    const hiddenFileInput = useRef(null);
    const activeLayout = activeTabLayout;

    useEffect(() => {
        // dispatch(fetch());
        dispatch(setSwitchHeaderAction(null));
    }, []);

    const handleClick = () => {
        (hiddenFileInput as any).current.click();
    };

    const changeLayout = (type: string) => {
        dispatch(
            setActivePageAction({
                type: 'images',
                modifier: 'upload'
            })
        );
    };

    return (
        <>
            <Head>
                <title>MapKids - Images</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <h2 className="mt-10 text-lg font-medium intro-y">
                {activeLayout.tab  !== 'list' && <span onClick={() => dispatch(
                    setActivePageAction({
                        type: 'images',
                        modifier: 'list'
                    })
                )} className="cursor-pointer inline-block pl-[30px] text-[12px] mr-[10px] back-arrow" />}
                Images Gallery
            </h2>
            {activeLayout.tab === 'list' ? (
                <>
                    <div className="grid grid-cols-12 gap-6 mt-5">
                        <div className="flex flex-wrap items-center col-span-12 mt-2 intro-y sm:flex-nowrap">
                            <button
                                onClick={() => changeLayout('upload')}
                                className="transition duration-200 border inline-flex items-center justify-center py-2 px-3 rounded-md font-medium cursor-pointer focus:ring-4 focus:ring-primary focus:ring-opacity-20 focus-visible:outline-none dark:focus:ring-slate-700 dark:focus:ring-opacity-50 [&amp;:hover:not(:disabled)]:bg-opacity-90 [&amp;:hover:not(:disabled)]:border-opacity-90 [&amp;:not(button)]:text-center disabled:opacity-70 disabled:cursor-not-allowed bg-primary border-primary text-white dark:border-primary mr-2 shadow-md"> Add
                                Upload New Images
                            </button>
                            {/*<div className="hidden mx-auto md:block text-slate-500"> Showing 1 to {count} of {count} entries</div>*/}
                        </div>
                    </div>
                    <ListItems locale={locale} />
                </>
            ) : (
                <>
                    <Photos uploadedFiles={[]} photos={[]} />
                </>
            )}
        </>
    );
}
Index.Layout = BackendLayout;

export async function getServerSideProps(context: any) {
    const { locale } = context;
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: { destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin` }
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}


