import Head from "next/head";
import { getSession } from "next-auth/react";
import BackendLayout from "../../components/Layout/BackendLayout";
// import CardLineChart from "../../components/Cards/CardLineChart";

export default function Dashboard({ session }: { session: any }) {
  if (!session) return <></>;

  return (
    <>
      <Head>
        <title>Mapkids - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="col-span-12 2xl:col-span-9 bg-pink">
          <div className="grid grid-cols-12 gap-6 bg-yellow">
              <div className="col-span-12 2xl:col-span-9 mt-4">
                  <div className="grid grid-cols-12 gap-6 mt-5">
                      <div className="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
                          <div className="relative zoom-in before:content-[''] before:w-[90%] before:shadow-[0px_3px_20px_#0000000b] before:bg-slate-50 before:h-full before:mt-3 before:absolute before:rounded-md before:mx-auto before:inset-x-0 before:dark:bg-darkmode-400/70">
                              <div className="p-5 box">
                                  <div className="flex">
                                      <div className="mt-6 text-3xl font-medium leading-8">
                                          10
                                      </div>
                                      <div className="mt-1 text-base text-slate-500">
                                          Available locations
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
                          <div className="relative zoom-in before:content-[''] before:w-[90%] before:shadow-[0px_3px_20px_#0000000b] before:bg-slate-50 before:h-full before:mt-3 before:absolute before:rounded-md before:mx-auto before:inset-x-0 before:dark:bg-darkmode-400/70">
                              <div className="p-5 box">
                                  <div className="flex">
                                      <div className="mt-6 text-3xl font-medium leading-8">
                                          5.5
                                      </div>
                                      <div className="mt-1 text-base text-slate-500">
                                          haha
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
                          <div className="relative zoom-in before:content-[''] before:w-[90%] before:shadow-[0px_3px_20px_#0000000b] before:bg-slate-50 before:h-full before:mt-3 before:absolute before:rounded-md before:mx-auto before:inset-x-0 before:dark:bg-darkmode-400/70">
                              <div className="p-5 box">
                                  <div className="flex">
                                      <div className="mt-6 text-3xl font-medium leading-8">
                                          5.5
                                      </div>
                                      <div className="mt-1 text-base text-slate-500">
                                          haha
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
                          <div className="relative zoom-in before:content-[''] before:w-[90%] before:shadow-[0px_3px_20px_#0000000b] before:bg-slate-50 before:h-full before:mt-3 before:absolute before:rounded-md before:mx-auto before:inset-x-0 before:dark:bg-darkmode-400/70">
                              <div className="p-5 box">
                                  <div className="flex">
                                      <div className="mt-6 text-3xl font-medium leading-8">
                                          5.5
                                      </div>
                                      <div className="mt-1 text-base text-slate-500">
                                          haha
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="mt-10 grid grid-cols-12">
              <div className="col-span-12 mt-6 xl:col-span-8">
                  <iframe
                      src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7248270.883477494!2d-89.096962565235!3d27.49431760538727!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88c1766591562abf%3A0xf72e13d35bc74ed0!2z0KTQu9C-0YDQuNC00LAsINCh0KjQkA!5e0!3m2!1sru!2sua!4v1684931663507!5m2!1sru!2sua"
                      width="95%" height="450"  loading="lazy"
                      referrerPolicy="no-referrer-when-downgrade" />
              </div>
              <div className="col-span-12 mt-6 xl:col-span-4">
                  <div className="flex items-center px-4 py-4 mb-3 box zoom-in">
                      <div className="flex-none w-10 h-10 overflow-hidden rounded-md image-fit">
                          <img
                              alt="Midone Tailwind HTML Admin Template" src="/images/backend/dashboard/123.webp" />
                      </div>
                      <div className="ml-4 mr-auto">
                          <div className="font-medium">Arnold Schwarzenegger</div>
                          <div className="text-slate-500 text-xs mt-0.5">04 May 2022</div>
                      </div>
                      <div
                          className="px-2 py-1 text-xs font-medium text-white rounded-full cursor-pointer bg-success"> 137
                          Sales
                      </div>
                  </div>
                  <div className="flex items-center px-4 py-4 mb-3 box zoom-in">
                      <div className="flex-none w-10 h-10 overflow-hidden rounded-md image-fit">
                          <img
                              alt="Midone Tailwind HTML Admin Template" src="/images/backend/dashboard/123.webp" />
                      </div>
                      <div className="ml-4 mr-auto">
                          <div className="font-medium">Arnold Schwarzenegger</div>
                          <div className="text-slate-500 text-xs mt-0.5">04 May 2022</div>
                      </div>
                      <div
                          className="px-2 py-1 text-xs font-medium text-white rounded-full cursor-pointer bg-success"> 137
                          Sales
                      </div>
                  </div>
                  <div className="flex items-center px-4 py-4 mb-3 box zoom-in">
                      <div className="flex-none w-10 h-10 overflow-hidden rounded-md image-fit">
                          <img
                              alt="Midone Tailwind HTML Admin Template" src="/images/backend/dashboard/123.webp" />
                      </div>
                      <div className="ml-4 mr-auto">
                          <div className="font-medium">Arnold Schwarzenegger</div>
                          <div className="text-slate-500 text-xs mt-0.5">04 May 2022</div>
                      </div>
                      <div
                          className="px-2 py-1 text-xs font-medium text-white rounded-full cursor-pointer bg-success"> 137
                          Sales
                      </div>
                  </div>
                  <div className="flex items-center px-4 py-4 mb-3 box zoom-in">
                      <div className="flex-none w-10 h-10 overflow-hidden rounded-md image-fit">
                          <img
                              alt="Midone Tailwind HTML Admin Template" src="/images/backend/dashboard/123.webp" />
                      </div>
                      <div className="ml-4 mr-auto">
                          <div className="font-medium">Arnold Schwarzenegger</div>
                          <div className="text-slate-500 text-xs mt-0.5">04 May 2022</div>
                      </div>
                      <div
                          className="px-2 py-1 text-xs font-medium text-white rounded-full cursor-pointer bg-success"> 137
                          Sales
                      </div>
                  </div>
              </div>


          </div>
      </div>

    </>
  );
}
Dashboard.Layout = BackendLayout;

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: { destination: `/auth/signin` },
    };
  }

  return {
    props: {
      session,
    },
  };
}
